---
title: "Data Modelling 2011-2012 Data Set"
author: "Niamh Harford 20251644"
date: "6/16/2021"
output: html_document
---


```{r}
# Load in necessary packages
suppressMessages(library(tidyverse))
suppressMessages(library(sjPlot))
suppressMessages(library(sjlabelled))
suppressMessages(library(sjmisc))
suppressMessages(library(MASS))
suppressMessages(library(car))
suppressMessages(library(arm))
suppressMessages(library(caret))
```


```{r}
# Load in all the data
load("Data/data1_11a.RData") 

head(data_11a)
nrow(data_11a)
```


```{r}
data_11a$Hypertension <-factor(ifelse(data_11a$Hypertension == "Yes", 1 ,0))

f1 <- glm(Hypertension ~ .,data=data_11a, family = binomial() )
f2 <- glm(Hypertension ~ Gender + Age+I(Age^2) + Race + Smoking + Diabetes + KidneyF + BMI+I(BMI^2) + PhysActivity + Alcohol + Salt + Potassium, data=data_11a, family = binomial())

anova(f1, f2, test="LRT")  # keep the quadratic terms


f3 <- glm(Hypertension ~ (Age+I(Age^2) + Race + Smoking + Diabetes
                     + KidneyF + BMI+I(BMI^2) + PhysActivity + Alcohol + Salt +
                     Potassium)*Gender, data=data_11a, family = binomial())
anova(f2,f3, test="LRT")  # so some interactions are good

Anova(f3)

f4 <-glm(Hypertension ~ (Age+I(Age^2) + BMI+I(BMI^2))*Gender+Race + Smoking + Diabetes + KidneyF + PhysActivity + Alcohol + Salt + Potassium, data=data_11a, family = binomial())
anova(f4,f3, test="LRT")  # confirms only need two interactions

anova(f4,f3, test="LRT")

Anova(f4)
# Continue with f4 - that has two quadratic terms and 4 interactions

f5 <- glm(Hypertension ~ (Age+I(Age^2) + BMI+I(BMI^2))*Gender+Race + Smoking + (Diabetes*Age) + KidneyF + PhysActivity + Alcohol + Salt + Potassium, data=data_11a, family = binomial())

anova(f4,f5, test="LRT")

Anova(f5)


f6 <- glm(Hypertension ~ (Age+I(Age^2) + BMI+I(BMI^2))*Gender+Race + (Smoking*Age) + (Diabetes*Age) + KidneyF + PhysActivity + Alcohol + Salt + Potassium, data=data_11a, family = binomial())

anova(f5,f6, test="LRT")
# Continue with f5 - that has two quadratic terms and 5 interactions
```


```{r}
summary(f4)
coefficients(f4) %>% exp() %>% round(digits = 5)
# Have to look at age and age^2 together with logistic regression
```


```{r}
summary(f5)
coefficients(f5) %>% exp() %>% round(digits = 5)
# Have to look at age and age^2 together with logistic regression
```

```{r}
# better than residualPlots
binnedplot(data_11a$Age, 
           residuals(f4, type = "response"), 
           nclass = NULL, 
           xlab = "Age", 
           ylab = "Average residual", 
           main = "Binned residual plot - Age", 
           cex.pts = 0.8, 
           col.pts = c("red","blue")[as.numeric(data_11a$Gender)], 
           col.int = "black")


binnedplot(fitted(f5), 
           residuals(f5, type = "response"), 
           nclass = NULL, 
           xlab = "Expected Values", 
           ylab = "Average residual", 
           main = "Binned residual plot", 
           cex.pts = 0.8, 
           col.pts = "blue", 
           col.int = "black")
```




```{r}
plot_model(f5, vline.color = "black", sort.est = TRUE,colors = "Accent")
# Age ^2 - actual significance it is different to 0 - p-value is small. But numerically it does not impact the response so not practically significant
# This plot is not good at interpreting Age and BMI
```

```{r, eval = F}
# library(gam)
# f5 <- glm(Hypertension ~ (Age+poly(Age,2)+BMI+bs(BMI,4))*Gender+Race + Smoking + Diabetes + KidneyF + PhysActivity + Alcohol + Salt + Potassium, data=data_11a, family = binomial())
plot_model(f4, type = "pred", terms = c("BMI"))
plot_model(f4, type = "pred", terms = c("BMI","Gender"))
plot_model(f4, type = "pred", terms = c("Age"))
plot_model(f4, type = "pred", terms = c("Age","Gender"))
plot_model(f4, type = "pred", terms = c("Potassium"))
plot_model(f4, type = "pred", terms = c("Potassium","Gender"))
plot_model(f4, type = "pred", terms = c("Smoking"))
plot_model(f4, type = "pred", terms = c("Smoking","Gender"))
plot_model(f5, type = "pred", terms = c("Diabetes"))
plot_model(f4, type = "pred", terms = c("Diabetes","Gender"))
plot_model(f4, type = "pred", terms = c("KidneyF"))
plot_model(f4, type = "pred", terms = c("KidneyF","Gender"))
plot_model(f4, type = "pred", terms = c("Race"))
plot_model(f4, type = "pred", terms = c("Race","Gender"))
plot_model(f4, type = "pred", terms = c("PhysActivity"))
plot_model(f4, type = "pred", terms = c("PhysActivity","Gender"))
plot_model(f4, type = "pred", terms = c("Alcohol"))
plot_model(f4, type = "pred", terms = c("Alcohol","Gender"))
plot_model(f4, type = "pred", terms = c("Salt"))
plot_model(f4, type = "pred", terms = c("Salt","Gender"))


```






```{r, fig.height=4,fig.width=16}
set.seed(123)
suppressMessages(library(randomForest))
suppressMessages(library(e1071))
suppressMessages(library(DALEX))
suppressMessages(library(rms))
suppressMessages(library(nnet))
suppressMessages(library(neuralnet))
suppressMessages(library(devtools))
suppressMessages(source_url('https://gist.githubusercontent.com/fawda123/7471137/raw/466c1474d0a505ff044412703516c34f1a4684a5/nnet_plot_update.r'))
```


```{r, eval=FALSE}
set.seed(123)

load("Data/data1_11a.RData")
fitControl <- trainControl(method = "repeatedcv", 
                           number = 10, 
                           repeats = 5, 
                           classProbs = TRUE, 
                           summaryFunction = twoClassSummary
                           )


nnet_grid <- expand.grid(decay = c(0.5, 0.1, 1e-2, 1e-3, 1e-4, 1e-5, 1e-6, 1e-7),                          size = c(3, 5, 10, 20))


nnetFit <- train(Hypertension ~ ., 
                 data = data_11a,
                 method = "nnet",
                 metric = "ROC",
                 trControl = fitControl,
                 tuneGrid = nnet_grid,
                 verbose = FALSE)


trellis.par.set(caretTheme())

plot(nnetFit)
ggplot(nnetFit)

whichTwoPct <- tolerance(nnetFit$results, metric = "ROC", 
                         tol = 2, maximize = TRUE)  
cat("best model within 2 pct of best:\n")
nnetFit$results[whichTwoPct,1:6]

# size = 3, decay =0.1
# size = 1, decay = 0.5

```



```{r}
model_log1 <- glm(Hypertension ~ (Age+I(Age^2) + BMI+I(BMI^2))*Gender+Race + Smoking + (Diabetes*Age) + KidneyF + PhysActivity + Alcohol + Salt + Potassium, data=data_11a, family = binomial())

model_rf <- randomForest(Hypertension ~ .,data_11a,importance = T)

varImpPlot(model_rf) 

model_nn <- nnet(Hypertension ~ ., data_11a, size = 1, decay = 0.5)




# save(model_log1, file = "model_log1.Rdata")
# save(model_rf, file =  "model_rf.Rdata")
# save(model_nn, file =  "model_nn.Rdata")


hypn <- as.numeric(data_11a$Hypertension)-1
ex_rf <- DALEX::explain(model_rf, data = data_11a, y = hypn, type = "classification")
ex_log <- DALEX::explain(model_log1, data = data_11a, y = hypn, type = "classification")
ex_nn <- DALEX::explain(model_nn, data = data_11a, y = hypn, type = "classification")



plot(model_profile(ex_rf, variables = c("Gender", "Race","Smoking", "Diabetes"))) + ggtitle("Response for Random Forest")
plot(model_profile(ex_rf, variables = c("KidneyF","PhysActivity", "Alcohol", "Salt"))) + ggtitle("Response for Random Forest")
plot(model_profile(ex_rf)) + ggtitle("Response for Random Forest")
plot(model_profile(ex_log, variables = c("Gender", "Race","Smoking", "Diabetes"))) + ggtitle("Response for Logistic Regression")
plot(model_profile(ex_log, variables = c("KidneyF","PhysActivity", "Alcohol", "Salt"))) + ggtitle("Response for Logistic Regression")
plot(model_profile(ex_log)) + ggtitle("Response for Logistic Regression")
plot(model_profile(ex_nn, variables = c("Gender", "Race","Smoking", "Diabetes"))) + ggtitle("Response for Neural Network")
plot(model_profile(ex_nn, variables = c("KidneyF","PhysActivity", "Alcohol", "Salt"))) + ggtitle("Response for Neural Network")
plot(model_profile(ex_nn)) + ggtitle("Response for Neural Network")


plot(model_profile(ex_log,groups="Gender")) + ggtitle("Response for Logistic Regression")
plot(model_profile(ex_rf,groups="Gender")) + ggtitle("Response for Random Forest")
plot(model_profile(ex_nn,groups="Gender")) + ggtitle("Response for Neural Network")




# look at model_performance and plot model_performance for nice way of getting roc and model summaries.

 

model_performance(ex_rf)
model_performance(ex_log)
model_performance(ex_nn)
plot(model_performance(ex_rf),model_performance(ex_log),model_performance(ex_nn), geom = "roc") 

```


```{r, include=TRUE, echo=FALSE, message=FALSE, warning=FALSE,fig.height=3, fig.cap="Appendix 1\\label{fig:Appendix1}",fig.show='hold'}
plot(model_profile(ex_rf, variable = "Gender")) + ggtitle("Response for Random Forest")+ theme(plot.title = element_text(size = 10))

```


```{r, include=TRUE, echo=FALSE, message=FALSE, warning=FALSE,fig.height=3, fig.cap="Appendix 2\\label{fig:Appendix2}",fig.show='hold'}

plot(model_profile(ex_rf, variable = "Race")) + ggtitle("Response for Random Forest")+ theme(plot.title = element_text(size = 10))

```
   
   
```{r, include=TRUE, echo=FALSE, message=FALSE, warning=FALSE,fig.height=3, fig.cap="Appendix 3\\label{fig:Appendix3}",fig.show='hold'}                   
plot(model_profile(ex_rf, variable = "Smoking")) + ggtitle("Response for Random Forest")+ theme(plot.title = element_text(size = 10))

```


```{r, include=TRUE, echo=FALSE, message=FALSE, warning=FALSE,fig.height=3, fig.cap="Appendix 4\\label{fig:Appendix4}",fig.show='hold'}

plot(model_profile(ex_rf, variable = "Diabetes")) + ggtitle("Response for Random Forest")+ theme(plot.title = element_text(size = 10))

```

```{r, include=TRUE, echo=FALSE, message=FALSE, warning=FALSE,fig.height=3, fig.cap="Appendix 5\\label{fig:Appendix5}",fig.show='hold'}
plot(model_profile(ex_rf, variable = "KidneyF")) + ggtitle("Response for Random Forest")+ theme(plot.title = element_text(size = 10))

```

```{r, include=TRUE, echo=FALSE, message=FALSE, warning=FALSE,fig.height=3, fig.cap="Appendix 6\\label{fig:Appendix6}",fig.show='hold'}
plot(model_profile(ex_rf, variable = "PhysActivity")) + ggtitle("Response for Random Forest")+ theme(plot.title = element_text(size = 10))
```

```{r, include=TRUE, echo=FALSE, message=FALSE, warning=FALSE,fig.height=3, fig.cap="Appendix 7\\label{fig:Appendix7}",fig.show='hold'}
plot(model_profile(ex_rf, variable ="Alcohol")) + ggtitle("Response for Random Forest")+ theme(plot.title = element_text(size = 10))
```

```{r, include=TRUE, echo=FALSE, message=FALSE, warning=FALSE,fig.height=3, fig.cap="Appendix 8\\label{fig:Appendix8}",fig.show='hold'}
plot(model_profile(ex_rf, variable ="Salt")) + ggtitle("Response for Random Forest")+ theme(plot.title = element_text(size = 10))
```

```{r, include=TRUE, echo=FALSE, message=FALSE, warning=FALSE,fig.height=3, fig.cap="Appendix 9\\label{fig:Appendix9}",fig.show='hold'}
plot(model_profile(ex_rf)) + ggtitle("Response for Random Forest")+ theme(plot.title = element_text(size = 10))
```

```{r, include=TRUE, echo=FALSE, message=FALSE, warning=FALSE,fig.height=3, fig.cap="Appendix 10\\label{fig:Appendix10}",fig.show='hold'}
plot(model_profile(ex_log, variable = "Gender")) + ggtitle("Response for Logistic Regression")+ theme(plot.title = element_text(size = 10))
```

```{r, include=TRUE, echo=FALSE, message=FALSE, warning=FALSE,fig.height=3, fig.cap="Appendix 11\\label{fig:Appendix11}",fig.show='hold'}
plot(model_profile(ex_log, variable = "Race")) + ggtitle("Response for Logistic Regression")+ theme(plot.title = element_text(size = 10))
```

```{r, include=TRUE, echo=FALSE, message=FALSE, warning=FALSE,fig.height=3, fig.cap="Appendix 12\\label{fig:Appendix12}",fig.show='hold'}
plot(model_profile(ex_log, variable = "Smoking")) + ggtitle("Response for Logistic Regression")+ theme(plot.title = element_text(size = 10))
```

```{r, include=TRUE, echo=FALSE, message=FALSE, warning=FALSE,fig.height=3, fig.cap="Appendix 13s\\label{fig:Appendix13}",fig.show='hold'}

plot(model_profile(ex_log, variable = "Diabetes")) + ggtitle("Response for Logistic Regression")+ theme(plot.title = element_text(size = 10))
```

```{r, include=TRUE, echo=FALSE, message=FALSE, warning=FALSE,fig.height=3, fig.cap="Appendix 14\\label{fig:Appendix14}",fig.show='hold'}
plot(model_profile(ex_log, variable = "KidneyF")) + ggtitle("Response for Logistic Regression")+ theme(plot.title = element_text(size = 10))
```

```{r, include=TRUE, echo=FALSE, message=FALSE, warning=FALSE,fig.height=3, fig.cap="Appendix 15\\label{fig:Appendix15}",fig.show='hold'}
plot(model_profile(ex_log, variable = "PhysActivity")) + ggtitle("Response for Logistic Regression")+ theme(plot.title = element_text(size = 10))
```

```{r, include=TRUE, echo=FALSE, message=FALSE, warning=FALSE,fig.height=3, fig.cap="Appendix 16\\label{fig:Appendix16}",fig.show='hold'}
plot(model_profile(ex_log, variable ="Alcohol")) + ggtitle("Response for Logistic Regression")+ theme(plot.title = element_text(size = 10))
```

```{r, include=TRUE, echo=FALSE, message=FALSE, warning=FALSE,fig.height=3, fig.cap="Appendix 17\\label{fig:Appendix17}",fig.show='hold'}
plot(model_profile(ex_log, variable ="Salt")) + ggtitle("Response for Logistic Regression")+ theme(plot.title = element_text(size = 10))
```

```{r, include=TRUE, echo=FALSE, message=FALSE, warning=FALSE,fig.height=3, fig.cap="Appendix 18\\label{fig.Appendix18}",fig.show='hold'}
plot(model_profile(ex_log)) + ggtitle("Response for Logistic Regression")+ theme(plot.title = element_text(size = 10))
```


```{r, include=TRUE, echo=FALSE, message=FALSE, warning=FALSE,fig.height=3, fig.cap="Appendix 19\\label{fig:Appendix19}",fig.show='hold'}
plot(model_profile(ex_nn, variable = "Gender")) + ggtitle("Response for Neural Network")+ theme(plot.title = element_text(size = 10))
```

```{r, include=TRUE, echo=FALSE, message=FALSE, warning=FALSE,fig.height=3, fig.cap="Appendix 20\\label{fig:Appendix20}",fig.show='hold'}
plot(model_profile(ex_nn, variable = "Race")) + ggtitle("Response for Neural Network")+ theme(plot.title = element_text(size = 10))
```

```{r, include=TRUE, echo=FALSE, message=FALSE, warning=FALSE,fig.height=3, fig.cap="Appendix 21\\label{fig:Appendix21}",fig.show='hold'}
plot(model_profile(ex_nn, variable = "Smoking")) + ggtitle("Response for Neural Network")+ theme(plot.title = element_text(size = 10))
```


```{r, include=TRUE, echo=FALSE, message=FALSE, warning=FALSE,fig.height=3, fig.cap="Appendix 22\\label{fig:Appendix22}",fig.show='hold'}
plot(model_profile(ex_nn, variable = "Diabetes")) + ggtitle("Response for Neural Network")+ theme(plot.title = element_text(size = 10))
```


```{r, include=TRUE, echo=FALSE, message=FALSE, warning=FALSE,fig.height=3, fig.cap="Appendix 23\\label{fig:Appendix23}",fig.show='hold'}
plot(model_profile(ex_nn, variable = "KidneyF")) + ggtitle("Response for Neural Network")+ theme(plot.title = element_text(size = 10))
```


```{r, include=TRUE, echo=FALSE, message=FALSE, warning=FALSE,fig.height=3, fig.cap="Appendix 24\\label{fig:Appendix24}",fig.show='hold'}
plot(model_profile(ex_nn, variable = "PhysActivity")) + ggtitle("Response for Neural Network")+ theme(plot.title = element_text(size = 10))
```

```{r, include=TRUE, echo=FALSE, message=FALSE, warning=FALSE,fig.height=3, fig.cap="Appendix 25\\label{fig:Appendix25}",fig.show='hold'}
plot(model_profile(ex_nn, variable ="Alcohol")) + ggtitle("Response for Neural Network")+ theme(plot.title = element_text(size = 10))
```


```{r, include=TRUE, echo=FALSE, message=FALSE, warning=FALSE,fig.height=3, fig.cap="Appendix 26\\label{fig:Appendix26}",fig.show='hold'}
plot(model_profile(ex_nn, variable ="Salt")) + ggtitle("Response for Neural Network") + theme(plot.title = element_text(size = 10))
```

```{r, include=TRUE, echo=FALSE, message=FALSE, warning=FALSE,fig.height=3, fig.cap="Appendix 27\\label{fig:Appendix27}",fig.show='hold'}
plot(model_profile(ex_nn)) + ggtitle("Response for Neural Network") + theme(plot.title = element_text(size = 10))

```




```{r}

# Gender and Race
plot(model_profile(ex_rf, variables = c("Gender","Race")), model_profile(ex_nn, , variables = c("Gender","Race")), model_profile(ex_log, , variables = c("Gender","Race"))) + ggtitle("Response for Gender and Race")

# Smoking and Diabetes
plot(model_profile(ex_rf, variables = c("Smoking", "Diabetes")), model_profile(ex_nn, , variables = c("Smoking", "Diabetes")), model_profile(ex_log, , variables = c("Smoking", "Diabetes"))) + ggtitle("Response for Smoking and Diabetes")


# KidneyF and Salt
plot(model_profile(ex_rf, variables = c("KidneyF","Salt")), model_profile(ex_nn, variables = c("KidneyF","Salt")), model_profile(ex_log, variables = c("KidneyF","Salt"))) + ggtitle("Response for Kidney Failure and Salt")


# Physical Activity and Alcohol
plot(model_profile(ex_rf, variables = c("PhysActivity", "Alcohol")), model_profile(ex_nn, , variables = c("PhysActivity", "Alcohol")), model_profile(ex_log, , variables = c("PhysActivity", "Alcohol"))) + ggtitle("Response for Physical Activity and Alcohol")

# Age, BMI and Potassium
plot(model_profile(ex_nn), model_profile(ex_rf), model_profile(ex_log)) + ggtitle("Response for Age, BMI and Potassium")
```


```{r, eval = FALSE}
library(condvis2)

#Click on show probs on the shiny app. The plots are like the partial dependence plots from DALEX, except the DALEX plots are averaging curves over all observations. You can see from both DALEX and condvis2 (switch from Age to BMI in the condvis2 menu) that the glm curve decreasing for high BMIs for males is likely not a good fit and probably does not make sense

condvis(data_11a, model=list(rf=model_rf, glm=model_log1, nn =model_nn), response="Hypertension", sectionvars=c("Age", "Gender"))
```


Training and Test Sets


```{r}
# Load in 2011/2012 data
load("Data/data1_11a.RData")

# Load in 2015/2016 Data
load("Data/hyp1.RData")
```



**Things to note **

+ 2011/2012 Data set will be my training and validation set

+ 2015/2016 Data set will be my test set

+ Training set where I am fitting the model 

+ Validation set where I am comparing results of the fit 

+ Test set is used to evaluate a model fit in the form of the test error rate


**Setting up the data **

```{r}
# Training Data

Train <- data_11a
  
#Test Data

Test <- hyp1
```



```{r}
set.seed(123)


Train$Hypertension <- factor(ifelse(Train$Hypertension == "Yes", 1 ,0))
Test$Hypertension <- factor(ifelse(Test$Hypertension == "Yes", 1 ,0))


f1 <-glm(Hypertension ~ (Age+I(Age^2) + BMI+I(BMI^2))*Gender+Race + Smoking + Diabetes + 
            KidneyF + PhysActivity + Alcohol + Salt +
            Potassium, data=Train, family = binomial())
 

f2 <- randomForest(Hypertension ~ .,Train, importance = T)


f3 <- nnet(Hypertension ~ ., Train, size = 1, decay = 0.5)


hypn <- as.numeric(Train$Hypertension)-1
ex_log <- DALEX::explain(f1, data = Train, y = hypn, type = "classification")
ex_rf <- DALEX::explain(f2, data = Train, y = hypn, type = "classification")
ex_nn <-  DALEX::explain(f3, data = Train, y = hypn, type = "classification")

 


# look at model_performance and plot model_performance for nice way of getting roc and model summaries.

 

model_performance(ex_rf)
model_performance(ex_log)
model_performance(ex_nn)

plot(model_performance(ex_rf),model_performance(ex_log), model_performance(ex_nn), geom = "roc")

```

```{r}
load("Data/hyp1.RData")
Test <- hyp1
Test$Hypertension <-factor(ifelse(Test$Hypertension == "Yes", 1 ,0))

hypn1 <- as.numeric(Test$Hypertension)-1
ex_log_test <- DALEX::explain(model_log1, data = Test, y = hypn1, type = "classification")
ex_rf_test <- DALEX::explain(model_rf, data = Test, y = hypn1, type = "classification")
ex_nn_test <-  DALEX::explain(model_nn, data = Test, y = hypn1, type = "classification")
model_performance(ex_rf_test)
model_performance(ex_log_test)
model_performance(ex_nn_test)
plot(model_performance(ex_rf_test),model_performance(ex_log_test),model_performance(ex_nn_test),
     geom = "roc")+ theme(plot.title = element_text(size = 10), plot.tag = element_text(size = 5)) + geom_line(lwd = 0.5) 
```





```{r}
suppressMessages(library(DALEXtra))
suppressMessages(library(workflows))
load("Data/glm_fit.RData")
load("Data/rf_fit.RData")
load("Data/final_nn.RData")

ex_log2 <- DALEX::explain(glm_fit, data = Test, y = hypn1, type = "classification")
ex_rf2 <- DALEX::explain(rf_fit, data = Test, y = hypn1, type = "classification")
ex_nn2 <-  DALEXtra::explain_tidymodels(final_nn, data = Test, y = hypn1, type = "classification")
 
# look at model_performance and plot model_performance for nice way of getting roc and model summaries.
 
model_performance(ex_rf)
model_performance(ex_log2)
model_performance(ex_nn2)
plot(model_performance(ex_rf2),model_performance(ex_log2), model_performance(ex_nn2), geom = "roc")
```

