---
title: "project_2011"
author: "Niamh Harford 20251644"
date: "6/3/2021"
output: html_document
---


```{r}
#Load in data
load("~/Documents/Masters/Dissertation/Project_Git/Data/data_11.RData")
```

```{r}
#Libraries
suppressMessages(library(tidyverse))
```


```{r}
#Count how much Na values in each variable - All Data

sum(data_11 %>%
  dplyr::summarise(count_hyp = sum(is.na(Hypertension)),
            count_gender = sum(is.na(Gender)),
            count_age = sum(is.na(Age)),
            count_race = sum(is.na(Race)),
            count_smoke20 = sum(is.na(Smoking)),
            count_diabetes10 = sum(is.na(Diabetes)),
            count_diabetes50 = sum(is.na(Insulin)),
            count_kidney = sum(is.na(KidneyF)),
            count_bmi = sum(is.na(BMI)),
            count_activity = sum(is.na(PhysActivity)),
            count_alcohol = sum(is.na(Alcohol)),
            count_salt = sum(is.na(Salt)),
            count_potassium = sum(is.na(Potassium))))

#1712 missing in total
```


```{r}
#removing the unknown "don't know" responses from the data

data_11a <- data_11 %>% filter(Hypertension != "Don't know") %>% filter(Diabetes != "Don't know") %>% filter(Smoking != "Don't know") %>%
  filter(KidneyF != "Don't know") %>% filter(Salt != "Don't know") %>%
  filter(Alcohol != "Don't know")

#readjusting the levels for each factor variable
data_11a <- data_11a %>% droplevels()
```

```{r}
#checking the levels are adjusted correctly
levels(data_11a$Hypertension)
levels(data_11a$Diabetes)
levels(data_11a$Smoking)
levels(data_11a$KidneyF)
levels(data_11a$Salt)
levels(data_11a$PhysActivity)
levels(data_11a$Alcohol)
table(data_11a$Hypertension)



#Reorder levels 

data_11a$Smoking <- relevel(data_11a$Smoking, "No")
data_11a$Diabetes <- relevel(data_11a$Diabetes, "No")
data_11a$Insulin <- relevel(data_11a$Insulin, "No")
data_11a$KidneyF <- relevel(data_11a$KidneyF, "No")
data_11a$PhysActivity <- relevel(data_11a$PhysActivity, "No")
data_11a$Alcohol <- relevel(data_11a$Alcohol, "No")
```

```{r,eval=FALSE}
save(data_11a, file = "data1_11a.RData")
load("data1_11a.RData")
```


```{r}
#Count how much Na values in each variable

sum(data_11a %>%
  summarise(count_hyp = sum(is.na(Hypertension)),
            count_gender = sum(is.na(Gender)),
            count_age = sum(is.na(Age)),
            count_race = sum(is.na(Race)),
            count_smoke20 = sum(is.na(Smoking)),
            count_diabetes10 = sum(is.na(Diabetes)),
            count_diabetes50 = sum(is.na(Insulin)),
            count_kidney = sum(is.na(KidneyF)),
            count_bmi = sum(is.na(BMI)),
            count_activity = sum(is.na(PhysActivity)),
            count_alcohol = sum(is.na(Alcohol)),
            count_salt = sum(is.na(Salt)),
            count_potassium = sum(is.na(Potassium))))

#52 missing values in total

```

#### Check the number of observaions in each data set when NAs removed

```{r}
nrow(data_11)
#5319
data_a <- na.omit(data_11)
nrow(data_a)
#4413
```

```{r}
nrow(data_11a)
#4364
data_11a <- na.omit(data_11a)
nrow(data_11a)
#4312
```


There seems to be no major difference between the two data sets (data1, with levels altered and data) when I omit the NA values


```{r}
glimpse(data_11a)
```


```{r}
levels(data_11a$Race)
levels(data_11a$Race) <- c("Mexican American", "Other Hispanic", "Non-Hispanic White","Non-Hispanic Black", "Other Race")
levels(data_11a$Race)
```




```{r, eval=F}
save(data_11a, file = "data1_11a.RData")
load("data1_11a.RData")
```