---
title: "Dissertation 2009/2010 Data"
author: "Niamh Harford 20251644"
date: "4/9/2021"
output: html_document
---

```{r}
#Packages I need
suppressMessages(library(nhanesA))
suppressMessages(library(tidyverse))
suppressMessages(library(ggplot2))
```


```{r, results='hide'}
#209/2010 data
smq_f <- nhanes('SMQ_F') 
demo_f <- nhanes('DEMO_F')
diq_f <- nhanes('DIQ_F') 
kiq_u_f <- nhanes('KIQ_U_F')
bmx_f <- nhanes('BMX_F') 
bpq_f<- nhanes('BPQ_F')
paq_f <- nhanes('PAQ_F')
alq_f <- nhanes('ALQ_F')
dr1tot_f <- nhanes('DR1TOT_F') #salt and potassium
```

```{r , results='hide'}
#Translate
demo_f <- nhanesTranslate('DEMO_F', c('RIAGENDR', 'RIDRETH1', 'RIDAGEYR'), data=demo_f)
bmx_f <- nhanesTranslate('BMX_F', 'BMXBMI', data=bmx_f)
smq_f <- nhanesTranslate('SMQ_F', 'SMQ020', data=smq_f)
diq_f <- nhanesTranslate('DIQ_F', c('DIQ010', 'DIQ050'), data=diq_f)
kiq_u_f <- nhanesTranslate('KIQ_U_F', c('KIQ022'), data=kiq_u_f)
bpq_f <- nhanesTranslate('BPQ_F', 'BPQ020', data=bpq_f)
paq_f <- nhanesTranslate('PAQ_F', 'PAQ665', data = paq_f)
alq_f <- nhanesTranslate('ALQ_F', 'ALQ101', data = alq_f)
dr1tot_f <- nhanesTranslate('DR1TOT_F', c('DBD100','DR1TPOTA'), data = dr1tot_f)
```

```{r}
#merging the data
comb1 <- merge(demo_f, smq_f)
comb2 <- merge(comb1, diq_f)
comb3 <- merge(comb2, kiq_u_f)
comb4 <- merge(comb3, bmx_f)
comb5 <- merge(comb4, bpq_f)
comb6 <- merge(comb5, paq_f)
comb7 <- merge(comb6, alq_f)
comb8 <- merge(comb7, dr1tot_f)
select_cols <- c('BPQ020','RIAGENDR', 'RIDAGEYR', 'RIDRETH1', 'SMQ020', 'DIQ010', 'DIQ050', 'KIQ022', 'BMXBMI', 'PAQ665', 'ALQ101', 'DBD100', 'DR1TPOTA')
comb_data <- comb8 %>% dplyr::select(all_of(select_cols))
```

```{r}
#Another way to join data
select_cols <- c('BPQ020','RIAGENDR', 'RIDAGEYR', 'RIDRETH1', 'SMQ020', 'DIQ010', 'DIQ050', 'KIQ022', 'BMXBMI', 'PAQ665','ALQ101', 'DBD100', 'DR1TPOTA')
data <- Reduce(merge, list(demo_f, smq_f, diq_f, kiq_u_f, bmx_f, bpq_f, paq_f, alq_f,dr1tot_f))
data <- data %>% dplyr::select(all_of(select_cols))
head(data)
```

```{r}
#Adjust the structure of the data
glimpse(data)
data$RIDAGEYR <- as.numeric(data$RIDAGEYR)
data$BMXBMI <- as.numeric(data$BMXBMI)
data$PAQ665 <- as.numeric(data$PAQ665)
data$ALQ101 <- as.numeric(data$ALQ101)
data$DR1TPOTA <- as.numeric(data$DR1TPOTA)
glimpse(data)
```


```{r}
#checking the responses for each factor variables
levels(data$BPQ020) #need to remove dont knows
levels(data$RIDRETH1) #dont need to fix anything
levels(data$SMQ020) #dont need to remove dont knows
levels(data$DIQ010) #need to remove dont knows
levels(data$DIQ050) #dont need to remove dont knows
levels(data$KIQ022) #need to remove dont knows
levels(data$DBD100) #need to remove dont knows
```

```{r}
#Rename the variables to meaningful names
data <- data %>% rename(Hypertension = BPQ020,
                        Gender = RIAGENDR,
                        Age = RIDAGEYR,
                        Race = RIDRETH1,
                        Smoking = SMQ020,
                        Diabetes = DIQ010,
                        Insulin = DIQ050,
                        KidneyF = KIQ022,
                        BMI = BMXBMI,
                        PhysActivity = PAQ665,
                        Alcohol = ALQ101,
                        Salt = DBD100,
                        Potassium = DR1TPOTA
                        )
```

```{r, eval=FALSE}
save(data, file = "data_09_10.RData")
load("data_09_10.RData") 
```

```{r}
#removing the unknown "dont know" answers from the data

data1 <- data %>% filter(Hypertension != "Don't know") %>% filter(Diabetes != "Don't know") %>% filter(KidneyF != "Don't know") %>% filter(Salt != "Don't know")

#readjusting the levels for each factor variable
data1 <- data1 %>% droplevels()

# save(data1, file = "data1_09_10.RData")
# load("data1_09_10.RData")
```


```{r}
glimpse(data1)
```


```{r}
#Count how much Na values in each variable

data1 %>%
  summarise(count_hyp = sum(is.na(Hypertension)),
            count_gender = sum(is.na(Gender)),
            count_age = sum(is.na(Age)),
            count_race = sum(is.na(Race)),
            count_smoke20 = sum(is.na(Smoking)),
            count_diabetes10 = sum(is.na(Diabetes)),
            count_diabetes50 = sum(is.na(Insulin)),
            count_kidney = sum(is.na(KidneyF)),
            count_bmi = sum(is.na(BMI)),
            count_activity = sum(is.na(PhysActivity)),
            count_alcohol = sum(is.na(Alcohol)),
            count_salt = sum(is.na(Salt)),
            count_potassium = sum(is.na(Potassium)))

#313 missing in alcohol variable


#Count how much Na values in each variable

data %>%
  summarise(count_hyp = sum(is.na(Hypertension)),
            count_gender = sum(is.na(Gender)),
            count_age = sum(is.na(Age)),
            count_race = sum(is.na(Race)),
            count_smoke20 = sum(is.na(Smoking)),
            count_diabetes10 = sum(is.na(Diabetes)),
            count_diabetes50 = sum(is.na(Insulin)),
            count_kidney = sum(is.na(KidneyF)),
            count_bmi = sum(is.na(BMI)),
            count_activity = sum(is.na(PhysActivity)),
            count_alcohol = sum(is.na(Alcohol)),
            count_salt = sum(is.na(Salt)),
            count_potassium = sum(is.na(Potassium)))

#a lot of the missing data for salt variable seemed to be in the don't know
```

```{r}
#Visualise the number of missing values

library(naniar)
gg_miss_var(data) + theme_bw() #All data
gg_miss_var(data1) + theme_bw() #Data with don't know responses removed

#DBD100 now has 0 missing values after removing don't know responses


gg_miss_upset(data = data, order.by = "freq")

gg_miss_upset(data = data1, order.by = "freq")

```

```{r}
nrow(data1)
#3931
data2 <- na.omit(data1)
nrow(data2)
#3592
```



```{r}
#I am going to try this code for the data dataset (no levels have been altered)
nrow(data)
#6059
data_a <- na.omit(data)
nrow(data_a)
#3614
```

There seems to be no major difference between the two datasets (data1, with levels altered and data) when I omit the NA values


```{r}
# save(data3, file = "data3_09_10.RData")
# load("data3_09_10.RData")
glimpse(data3)
```









```{r}
temp = data.frame(predicted = predict(log_reg), actual = (data3$Hypertension))
ggplot(data = temp, aes(x = predicted, y = actual)) + geom_point() + geom_smooth(method = lm, se = F) + labs(title = "Actual vs Predicted Mesostigmata Abundance Values")
```

