---
title: "Dissertation"
author: "Niamh Harford 20251644"
date: "`r format(Sys.time(), '%d %B, %Y')`"
output: pdf_document
linestretch: 1.5
---


<h2>**Introduction**</h2>

<body>
<h3>**Hypertension**</h3>

Hypertension is an important condition that commonly leads to many serious illnesses including stroke and heart disease (Sakr et al., 2018), furthermore it is described as a common, chronic, age-related disorder, which entails severe cardiovascular and kidney complications (Staessen, Wang, Bianchi and Birkenhäger, 2003). It mainly arises as a complex quantitative characteristic that is affected by varying relationships of genetic and environmental factors, whereby these characteristics have turned out to be extremely harmful habits that have caused weakened heart function due to increased blood pressure (Staessen, Wang, Bianchi and Birkenhäger, 2003). There are many factors that may contribute to the permanent rise of blood pressure and it can more than often be a result of many factors working cooperatively. Hypertension prevalence has been seen to rise with age, disregarding both the type of blood pressure measurement and the operative thresholds used for diagnosis (Staessen, Wang, Bianchi and Birkenhäger, 2003). There are many things to consider as contributing factors to hypertension as age increases. There are many habits for example exercise that as people get older, they may refrain from. Age would be an interesting trait to explore interactions with multiple other factors.he The American Heart Association have stated that the estimates for hypertension prevalence are comparable between both men and women, are highest among African Americans where 44% of people surveyed that had hypertension were African American, and showed that only 53% of all hypertensive adults have their blood pressure under some control (Go et al., 2013). This statement highlights how the different racial groups may have an effect of the prevalence of hypertension, which association may not have been initially considered. An interesting statistic has revealed that hypertension is considered in the group of risk factors for cardiovascular disease that caused up to 17.7 million deaths around the world in 2015 alone (López-Martínez, Núñez-Valdez, Crespo and García-Díaz, 2020). This figure reveals how serious hypertension is to our health and the effect it will continue to have on life.
</body>  
  
<body>  
<h3>**What might cause hypertension**</h3>

Here I will discuss the variables
</body>

<body>
<h3>**NHANES Data**</h3>

The data that I will use is from the  National Health and Nutrition Examination Survey (NHANES). NHANES is a program of studies designed to evaluate the health and nutritional status of both adults and children in America (NHANES - About the National Health and Nutrition Examination Survey, 2021). This data is published online and can be publicly accessed for statistical analysis. The survey is distinctive in that it uses both interviews and physical examinations to assess the health of the people who are being sampled. The NHANES program was established in the early 1960s and has been ran as a series of surveys focusing on different population groups or health topics (NHANES - About the National Health and Nutrition Examination Survey, 2021). In 1999, the survey became a sustained program that has a changing focus on a variety of health and nutrition measurements to meet emerging needs. NHANES survey a nationally representative sample of about 5,000 persons annually (NHANES - About the National Health and Nutrition Examination Survey, 2021). The NHANES interview includes many components in particular demographic, socioeconomic, dietary, and health-related questions. The examination component consists of medical, dental, and physiological measurements, as well as laboratory tests dispenced by highly trained medical personnel. Findings from surveys such as NHANES will be used to discover the prevalence of major diseases and risk factors for diseases (NHANES - About the National Health and Nutrition Examination Survey, 2021).


<h3>**Related Work**</h3>

<h2>**Methods**</h2>

<h3>**Setting Up NHANES Data**</h3>

I chose to use the 2011/2012 data set and I obtained the variables that were necessary to my study from the NHANES data set, primarily from following the introductory nhanesA vignette. Firstly, I installed the package "nhanesA" using install.packages("nhanesA") and then loaded the packages using library(nhanesA). Following this, I proceeded to import five data files from the 2009-2010 data. Four of these data files came from the questionnaire data (SMQ_F, DIQ_F, KIQ_F, BPQ_F) while the fifth came from the examination data (BMX_F). SMQ_F contains data on smoking use, DIQ_F contains data on diabetes, KIQ_F contains data on kidney conditions, BPQ_F contains data on blood pressure and cholesterol and BMX_F contains data on body measures. Along with these I also imported the data that contained the demographics table (DEMO_F). I merged all the data together to form one data set, where I then choose twelve explanatory variables, in addition to one response variable. The explanatory variables from the NHANES data set are RIAGENDR, RIDAGEYR, RIDRETH1, SMQ020, DIQ010, DIQ050, KIQ022, BMXBMI, PAQ665, ALQ101, DRQSPREP and DR1TPOTA. These variables respectively correspond to gender, age, race, smoking, diabetes, insulin intake, kidney failure, bmi, physical activity, alcohol use, salt use and potassium levels. The response variable is BPQ020, which corresponds to Hypertension. Each variable contained a question where the particpants response or measurements were recorded. The variable RIAGENDR is the gender of the participants of the NHANES data set. RIDAGEYR is the age in years of the participant at the time of screening. Individuals 80 and over are top-coded at 80 years of age. RIDRETH1 is the re-code of reported race and ethnicity information. These three variables have been taken from the demographic table. SMQ020 is where a participant is defined as smoker if they answer "Yes" to having smoked more than 100 cigarettes during their lifetime. DIQ010 is where participants have diabetes if the answer presents “Yes or “Borderline” to the question have ever been told that you have diabetes and DIQ050 is whether the participant is now taking insulin or not. KIQ022 relates to chronic kidney disease (CKD) which is defined as “Yes” response to the question have you ever told by a health care provider you have weak or failing kidneys. BMXBMI is the measure of Body Mass Index (kg/m**2). PAQ665 is in a typical week do you do any moderate-intensity sports, fitness, or recreational activities that cause a small increase in breathing or heart rate such as brisk walking, bicycling, swimming, or volleyball for at least 10 minutes continuously. ALQ101 is in any one year, have you/has SP had at least 12 drinks of any type of alcoholic beverage? By a drink, I mean a 12 oz. beer, a 5 oz. glass of wine, or a one and a half ounces of liquor. DBD100 is how often do you add ordinary salt to your food at the table. This is a categorical variable with several factors.  


<body>
<h2>**Modelling**</h2>


<h2>**References**</h2>

* Sakr, S., Elshawi, R., Ahmed, A., Qureshi, W., Brawner, C., Keteyian, S., Blaha, M. and Al-Mallah, M., 2018. Using machine learning on cardiorespiratory fitness data for predicting hypertension: The Henry Ford ExercIse Testing (FIT) Project. *PLOS ONE,* 13(4), p.e0195344.
* Staessen, J., Wang, J., Bianchi, G. and Birkenhäger, W., 2003. Essential hypertension. *The Lancet*, 361(9369), pp.1629-1641.
* World Health Organization. World Health Statistics 2017: *Monitoring Health for The SDGs.* arXiv:1011.1669v3 (2017).
* Go, A.S., Mozaffarian, D., Roger, V.L., Benjamin, E.J., Berry, J.D., Borden, W.B., Bravata, D.M., Dai, S., Ford, E.S., Fox, C.S. and Franco, S., 2013. Heart disease and stroke statistics—2013 update: a report from the American Heart Association. *Circulation*, 127(1), pp.e6-e245.
* López-Martínez, F., Núñez-Valdez, E., Crespo, R. and García-Díaz, V., 2020. An artificial neural network approach for predicting hypertension using NHANES data. *Scientific Reports*, 10(1).
* Cdc.gov. 2021. NHANES - About the National Health and Nutrition Examination Survey. [online] Available at: <https://www.cdc.gov/nchs/nhanes/about_nhanes.htm> [Accessed 31 May 2021].








* For 1999–2010, NHANES content was modified biannually as components were added, changed, or removed. Changes were also made to target new age groups, modify data collection methods, and update technologies. Prior to biannual changes, NHANES conducted pilot tests of new or revised survey material as part of the ongoing data collection.
* Rather, a complex, multistage probability sampling design was used to select a sample representative of the civilian noninstitutionalized household population of the United States.




**Assumptions for logistic regression: **
+ Basic assumptions that must be met for logistic regression include independence of errors (the observations to be independent of each other), linearity in the logit for continuous variables ( it requires that the independent variables are linearly related to the log odds), absence of multicollinearity (This means that the independent variables should not be too highly correlated with each other), and lack of strongly influential outliers.

